import { PrismaClient } from "@prisma/client";

/**
 * Notifications are generated by application workflows (leave, attendance, reports, etc).
 * We intentionally skip seeding static notifications here so the UI only reflects real data.
 */
export const seedNotifications = async (_prisma: PrismaClient) => {
  void _prisma;
  // No-op seed. Notifications come from runtime features.
};
